<?php
	$DATABASE_HOST = 'localhost';
	$DATABASE_USER = 'root';
	$DATABASE_PASSWORD = '123';
	$DATABASE_NAME = 'dht11'; 
	$DATABASE_CONNECT = mysqli_connect($DATABASE_HOST, $DATABASE_USER, $DATABASE_PASSWORD, $DATABASE_NAME);
	if(!$DATABASE_CONNECT)
	{
		die('连接失败: ' . mysqli_error($DATABASE_CONNECT));
	}
	mysqli_query ($DATABASE_CONNECT, 'SET NAMES UTF8');
?>